// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Int from "bs-platform/lib/es6/belt_Int.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

var count = document.getElementById("count");

var plusBtn = document.getElementById("plus-one");

var minusBtn = document.getElementById("minus-one");

function removeLastClass(param) {
  var theClass = Caml_array.get(count.classList, 1);
  return count.classList.remove(theClass);
}

function addClass(className) {
  removeLastClass(undefined);
  return count.classList.add(className);
}

function getCount(param) {
  var theCount = Caml_array.get(count.innerText.split(" "), 2);
  var number = Belt_Int.fromString(theCount);
  if (number !== undefined) {
    return number;
  } else {
    return 0;
  }
}

function updateClass(param) {
  var realCount = getCount(undefined);
  if (realCount > 0) {
    return addClass("count-positive");
  } else if (realCount < 0) {
    return addClass("count-negative");
  } else {
    return addClass("count-zero");
  }
}

function updateCounter(number) {
  var newCount = getCount(undefined) + number | 0;
  var realCount = newCount === 0 ? "zero" : String(newCount);
  count.innerText = "Count is " + realCount;
  return updateClass(undefined);
}

function handleEvent(action) {
  if (action) {
    return updateCounter(-1);
  } else {
    return updateCounter(1);
  }
}

plusBtn.addEventListener("click", (function (param) {
        return updateCounter(1);
      }));

minusBtn.addEventListener("click", (function (param) {
        return updateCounter(-1);
      }));

export {
  count ,
  plusBtn ,
  minusBtn ,
  removeLastClass ,
  addClass ,
  getCount ,
  updateClass ,
  updateCounter ,
  handleEvent ,
  
}
/* count Not a pure module */
